baseURL      = "https://lomolive.vercel.app"
languageCode = "en-us"
title        = 'Lomo website'


[params]
  description = "Lomo's website"
  keywords    = "Lomo's website"

  [params.author]
    name = 'Al-ameen Musa'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"
